### ISSUE TITLE
Uncaught TypeError: atom.workspace.paneContainer.activePane.getActiveItem(...).getPath is not a f...

### ISSUE THREAD

**Issue by teknologist** [feens/atom-stash-tabs#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11
**Thrown From**: [stash-tabs](https://github.com/feens/atom-stash-tabs) package, v0.1.0
### Stack Trace

Uncaught TypeError: atom.workspace.paneContainer.activePane.getActiveItem(...).getPath is not a function

```
At /Users/eric/.atom/packages/stash-tabs/lib/stash-tabs.coffee:11

TypeError: atom.workspace.paneContainer.activePane.getActiveItem(...).getPath is not a function
    at Object.module.exports.stash (/Users/eric/.atom/packages/stash-tabs/lib/stash-tabs.coffee:11:75)
    at atom-workspace.<anonymous> (/Users/eric/.atom/packages/stash-tabs/lib/stash-tabs.coffee:6:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -2:01.6.0 enhanced-tabs:toggle (atom-text-editor.editor.mini.is-focused)
  4x -1:57.3.0 pane:show-next-item (button.btn.icon.enablement.icon-playback-play)
  7x -1:40 enhanced-tabs:toggle (atom-text-editor.editor.mini.is-focused)
     -1:10.6.0 pane:reopen-closed-item (ul.list-inline.tab-bar.inset-panel)
     -0:07.8.0 fuzzy-finder:toggle-file-finder (div.panels)
     -0:06.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:06.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 command-palette:toggle (div.panels)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 stash-tabs:stash (div.panels)
```
### Config

``` json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "atom-dark-fusion-syntax"
    ],
    "disabledPackages": [
      "git-show",
      "css-color-highlighting",
      "git-grep",
      "language-groovy-cloned-from-java",
      "atom-angularjs",
      "autocomplete-polymer",
      "file-type-icons",
      "color-tabs",
      "multirow-tabs",
      "atom-no-tab-close-button",
      "new-tab"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-dark-fusion-syntax, v1.1.0
atom-handlebars, v1.2.0
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
close-other-tabs, v0.1.0
color-picker, v2.0.13
command-logger, v0.23.0
editor-stats, v0.17.0
file-icons, v1.6.12
file-types, v0.5.1
jsformat, v0.9.0
jshint, v1.8.3
jsonlint, v1.1.2
language-java, v0.16.1
language-puppet, v0.15.0
language-spacebars, v0.2.2
linter, v1.11.2
linter-csslint, v1.1.0
linter-flow, v4.0.0
linter-handlebars, v2.2.0
linter-javac, v1.3.0
linter-jshint, v1.2.1
linter-perl, v0.7.0
linter-puppet-lint, v0.6.1
linter-scss-lint, v2.4.0
linter-swiftc, v2.0.0
linter-xmllint, v1.1.0
meteor-api, v2.20.0
mixed-indent-warning, v0.2.0
nucleus-dark-ui, v0.6.12
one-tab, v0.8.0
package-sync, v0.2.0
pigments, v0.19.0
pretty-json, v0.4.1
project-colorize, v0.2.0
project-manager, v2.6.5
seti-icons, v0.4.5
stash-tabs, v0.1.0
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by teknologist** [comment]
DUP
